markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
kramdown:
  math_engine: katex
plugins:
  - jekyll-include-cache
  - jekyll-katex
minimal_mistakes_skin: "default"
locale: "en-US"
title: "My Awesome Site"
subtitle: "Version 2.0"
name: "Jinwook Kim"
description: "A flexible Jekyll theme for your blog or site with a minimalist aesthetic."
url: "https://LeeSeongWoo513.github.io"
repository: "LeeSeongWoo513/LeeSeongWoo513.github.io"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      # comments: true
      # share: true
      # related: true

# Outputting
permalink: /:categories/:title/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
